<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <UserSecretsId>aspnet-Tortis.Iam.Server-FE1ACAB7-3021-42FA-A1E8-2E63E219B8E2</UserSecretsId>
    </PropertyGroup>
    
    <ItemGroup>
        <InternalsVisibleTo Include="OpenIdConnectTests" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="EFCore.NamingConventions" Version="8.0.3" />
        <PackageReference Include="Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore" Version="8.0.11"/>
        <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="8.0.11"/>
        <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.11" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.11"/>
        <PackageReference Include="OpenIddict" Version="6.1.0" />
        <PackageReference Include="OpenIddict.AspNetCore" Version="6.1.0" />
        <PackageReference Include="OpenIddict.EntityFrameworkCore" Version="6.1.0" />
        <PackageReference Include="OpenIddict.Quartz" Version="6.1.0" />
        <PackageReference Include="Quartz.Extensions.Hosting" Version="3.13.1" />
        <PackageReference Include="Microsoft.FluentUI.AspNetCore.Components" Version="4.10.4" />
        <PackageReference Include="Microsoft.FluentUI.AspNetCore.Components.Icons" Version="4.10.4" />
        <PackageReference Include="Microsoft.Extensions.Diagnostics.HealthChecks" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Data\Migrations\" />
    </ItemGroup>

</Project>
