<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>

    <UserSecretsId>aspnet-Tortis.Iam.Server-FE1ACAB7-3021-42FA-A1E8-2E63E219B8E2</UserSecretsId>
<!--    <PublishSingleFile>true</PublishSingleFile>-->
<!--    <SelfContained>false</SelfContained>-->
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="OpenIdConnectTests" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="EFCore.NamingConventions" />
    <PackageReference Include="Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" />
    <PackageReference Include="Microsoft.Extensions.Diagnostics.HealthChecks" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" />
    <PackageReference Include="OpenIddict" />
    <PackageReference Include="OpenIddict.AspNetCore" />
    <PackageReference Include="OpenIddict.EntityFrameworkCore" />
    <PackageReference Include="OpenIddict.Quartz" />
    <PackageReference Include="Quartz.Extensions.Hosting" />
    <PackageReference Include="Quartz.Serialization.SystemTextJson" />
    <PackageReference Include="System.Data.SQLite" />
    <PackageReference Include="Ulid" />
    <PackageReference Include="Serilog" />
    <PackageReference Include="Serilog.AspNetCore" />
    <PackageReference Include="Serilog.Enrichers.Span" />
    <PackageReference Include="Serilog.Sinks.Async" />
    <PackageReference Include="Serilog.Sinks.Console" />
    <PackageReference Include="Serilog.Sinks.OpenTelemetry" />
    <PackageReference Include="OpenTelemetry.Extensions.Hosting" />
    <PackageReference Include="OpenTelemetry.Exporter.OpenTelemetryProtocol" />
    <PackageReference Include="OpenTelemetry.Instrumentation.Runtime" />
    <PackageReference Include="OpenTelemetry.Instrumentation.AspNetCore" />
    <PackageReference Include="OpenTelemetry.Instrumentation.EntityFrameworkCore" />

    <PackageReference Include="Microsoft.FluentUI.AspNetCore.Components" />
    <PackageReference Include="Microsoft.FluentUI.AspNetCore.Components.Icons" />
    <PackageReference Include="Microsoft.FluentUI.AspNetCore.Components.DataGrid.EntityFrameworkAdapter" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Data\qrtz_sqlite_schema.sql" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Tortis.Iam.OpenIddict.JwtBearer\Tortis.Iam.OpenIddict.JwtBearer.csproj" />
  </ItemGroup>

</Project>
